import {Inter} from "next/font/google";
import "./globals.css";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[#343B71] min-h-full flex">
          <div className="max-w-[400px] mx-auto flex-auto text-white font-display py-5 px-2.5 sm:px-0">{children}</div>
        </div>
      </body>
    </html>
  );
}
